services:
  db:
    image: postgres:16
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - restaurant_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/RestaurantReservation.WebApi/Dockerfile
    container_name: restaurant_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_ROLE=${ADMIN_ROLE}
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};    
    ports:
      - "5003:8080"
    depends_on:
      - db

volumes:
  restaurant_pgdata: